# Mostly grayscale theme for helix without being too contrasty

# Syntax highlighting
"type" = { fg = "gray-light", modifiers = ["bold"] }
"type.builtin" = "gray-medium"
"constructor" = { fg = "gray-light", modifiers = ["bold"] }
"constant" = "gray-medium"
"constant.builtin" = { fg = "gray-medium", modifiers = ["italic"] }
"constant.builtin.boolean" = { fg = "accent-blue", modifiers = ["bold"] }
"constant.character.escape" = "accent-purple"
"constant.numeric" = "gray-medium"
"string" = "gray-medium"
"string.regexp" = { fg = "accent-purple", modifiers = ["italic"] }
"string.special" = "gray-light"
"comment" = { fg = "gray-dim", modifiers = ["italic"] }
"variable" = "gray-main"
"variable.parameter" = { fg = "gray-light", modifiers = ["italic"] }
"variable.builtin" = { fg = "accent-blue", modifiers = ["italic"] }
"variable.other.member" = "gray-main"
"label" = "gray-dim"
"keyword" = { fg = "gray-bright", modifiers = ["bold"] }
"keyword.directive" = { fg = "accent-orange", modifiers = ["bold"] }
"keyword.storage.type" = { fg = "gray-bright", modifiers = ["bold"] }
"keyword.control" = { fg = "gray-bright", modifiers = ["bold"] }
"keyword.operator" = "gray-medium"
"function" = { fg = "gray-light", modifiers = ["bold"] }
"function.builtin" = "gray-medium"
"function.method" = { fg = "gray-light", modifiers = ["bold"] }
"function.macro" = { fg = "accent-purple", modifiers = ["bold"] }
"punctuation" = "gray-dim"
"punctuation.delimiter" = "gray-dim"
"punctuation.bracket" = "gray-medium"
"tag" = { fg = "gray-light", modifiers = ["bold"] }
"attribute" = "gray-medium"
"namespace" = "gray-medium"
"special" = "accent-orange"
"operator" = "gray-medium"

# Markup
"markup.heading.marker" = "gray-dim"
"markup.heading.1" = { fg = "gray-bright", modifiers = ["bold"] }
"markup.heading.2" = { fg = "gray-light", modifiers = ["bold"] }
"markup.heading.3" = { fg = "gray-medium", modifiers = ["bold"] }
"markup.heading.4" = { fg = "gray-medium", modifiers = ["bold", "italic"] }
"markup.heading.5" = { fg = "gray-dim", modifiers = ["bold"] }
"markup.heading.6" = { fg = "gray-dim", modifiers = ["bold", "italic"] }
"markup.list" = "gray-dim"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "accent-blue", modifiers = ["underlined"] }
"markup.link.text" = { fg = "gray-light", modifiers = ["underlined"] }
"markup.raw.block" = { bg = "background-subtle" }
"markup.raw.inline" = "accent-green"

# UI
"ui.background" = { bg = "background" }
"ui.text" = "gray-main"
"ui.text.focus" = { fg = "gray-bright", bg = "background-highlight", modifiers = ["bold"] }
"ui.text.inactive" = "gray-dim"
"ui.text.directory" = { fg = "accent-blue", modifiers = ["bold"] }
"ui.linenr" = { fg = "gray-dim", bg = "background-subtle" }
"ui.linenr.selected" = { fg = "gray-medium", bg = "background-active" }
"ui.selection" = { fg = "gray-bright", bg = "background-selection" }
"ui.selection.primary" = { fg = "gray-bright", bg = "background-active" }
"ui.cursor" = { fg = "background", bg = "gray-main" }
"ui.cursor.primary" = { fg = "background", bg = "gray-light" }
"ui.cursor.match" = { fg = "gray-bright", bg = "background-match" }
"ui.cursorline.primary" = { bg = "background-line" }
"ui.highlight" = { bg = "background-highlight" }
"ui.statusline" = { fg = "gray-main", bg = "background-statusline" }
"ui.statusline.inactive" = { fg = "gray-dim", bg = "background-statusline-inactive" }
"ui.statusline.normal" = { fg = "accent-blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "accent-green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "accent-purple", modifiers = ["bold"] }
"ui.popup" = { fg = "gray-main", bg = "background-popup" }
"ui.window" = "gray-dim"
"ui.help" = { fg = "gray-main", bg = "background-popup" }
"ui.gutter" = { bg = "background-subtle" }
"ui.menu" = { fg = "gray-main", bg = "background-popup" }
"ui.menu.selected" = { fg = "gray-bright", bg = "background-active", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "gray-dim", bg = "background-highlight" }
"ui.virtual" = "gray-faint"
"ui.virtual.ruler" = { bg = "background-subtle" }
"ui.virtual.inlay-hint" = { fg = "gray-faint", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "accent-orange", modifiers = ["bold"] }
"ui.virtual.indent-guide" = "gray-faint"
"ui.virtual.whitespace" = "gray-faint"
"ui.bufferline" = { fg = "gray-dim", bg = "background-subtle" }
"ui.bufferline.active" = { fg = "gray-main", bg = "background", modifiers = ["bold"] }

# Diagnostics
"diagnostic.error" = { underline = { color = "accent-red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "accent-orange", style = "curl" } }
"diagnostic.info" = { underline = { color = "accent-blue", style = "curl" } }
"diagnostic.hint" = { fg = "gray-dim", modifiers = ["italic"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"error" = "accent-red"
"warning" = "accent-orange"
"info" = "accent-blue"
"hint" = "gray-medium"

# Diffs
"diff.plus" = { fg = "accent-green", bg = "background-diff-add" }
"diff.plus.gutter" = "accent-green"
"diff.minus" = { fg = "accent-red", bg = "background-diff-remove" }
"diff.minus.gutter" = "accent-red"
"diff.delta" = { fg = "accent-orange", bg = "background-diff-change" }
"diff.delta.gutter" = "accent-orange"

[palette]
background = "#1a1a1a"
background-subtle = "#242424"
background-popup = "#2a2a2a"
background-statusline = "#333333"
background-statusline-inactive = "#2a2a2a"
background-line = "#222222"
background-highlight = "#2d2d2d"
background-active = "#383838"
background-selection = "#404040"
background-match = "#4a4a4a"
gray-dark = "#0f0f0f"
gray-faint = "#4a4a4a"
gray-dim = "#666666"
gray-medium = "#888888"
gray-main = "#b0b0b0"
gray-light = "#c8c8c8"
gray-bright = "#e0e0e0"
background-diff-add = "#1a2a1a"
background-diff-remove = "#2a1a1a"
background-diff-change = "#2a2a1a"
accent-red = "#cc6666"
accent-green = "#99cc99"
accent-blue = "#81a2be"
accent-orange = "#de935f"
accent-purple = "#b294bb"
white = "#e0e0e0"
gray = "#888888"
darkgray = "#333333"
black = "#1a1a1a"
cursor = "#c8c8c8"
selected = "#383838"
red = "#cc6666"
green = "#99cc99"
orange = "#de935f"
